language: php

env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
    - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
    - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi


script:
  - vendor/phpunit/phpunit/phpunit
